# server
server:
  port: 8888

# upload path @AuthController /upload
me:
  upload:
    path: E:/blogFile/

# mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cbse_blog?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  #static
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${me.upload.path}
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${me.upload.path}
  #spring.mvc.static-path-pattern=/**
  #spring.resources.static-locations=classpath:/META-INF/resources/,classpath:/resources/,\
  #classpath:/static/,classpath:/public/,file:${me.upload.path}

  servlet:
    # file upload
    multipart:
      # max file size of single upload
      max-file-size: 20MB
      # max file size of a single HTTP request
      max-request-size: 20MB

  # redis

  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 10000
    pool:
      max-active: 8 #连接池最大连接数（负值表示没有限制）
      max-wait: -1 #连接池最大阻塞等待时间（负值表示没有限制）
      max-idle: 8 #连接池最大空闭连接数
      min-idle: 0 #连接汉最小空闲连接数
      timeout: 10000 #连接超时时间（毫秒）

# mybatis-plus
mybatis-plus:
  configuration:
    # log
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # logical delete field
      logic-delete-field: delFlag
      # represent delete
      logic-delete-value: 1
      # represent not delete
      logic-not-delete-value: 0
      # primary key auto increment
      id-type: auto
