# server
server:
  port: 8888

# mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cbse_blog?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  servlet:
    # file upload
    multipart:
      # max file size of single upload
      max-file-size: 20MB
      # max file size of a single HTTP request
      max-request-size: 20MB

# redis


# mybatis-plus
mybatis-plus:
  configuration:
    # log
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # logical delete field
      logic-delete-field: delFlag
      # represent delete
      logic-delete-value: 1
      # represent not delete
      logic-not-delete-value: 0
      # primary key auto increment
      id-type: auto